baseURL = "https://www.eclipse.dev/emfcloud"
DefaultContentLanguage = "en"
title = "EMF Cloud"
theme = "syna"

[markup.goldmark.renderer]
unsafe = true

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[params]
  name = "Eclipse Foundation"
  description = "EMF Cloud"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    #favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#2490c6"
    secondary = "#faf9f9"
    success = "#008f54"
    info = "#00c9dc"
    warning = "#fdf314"
    danger = "#dc1200"
    light = "#faf9f9"
    dark = "#1e2624"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = ""
  name = "Home"
  weight = 10

[[menu.main]]
  url = "support"
  name = "Support"
  weight = 20

[[menu.main]]
  url = "documentation"
  name = "Documentation"
  weight = 30

[[menu.main]]
  url = "contact"
  name = "Contact"
  weight = 60

[[menu.main]]
  url = "https://github.com/eclipse-emfcloud/emfcloud"
  name = "GitHub"
  weight = 60

[[menu.footer]]
  url = "https://jsonforms.io"
  name = "JSON Forms"
  weight = 15

[[menu.footer]]
  url = "https://eclipse.dev/glsp"
  name = "Eclipse GLSP"
  weight = 10

[[menu.footer]]
  url = "https://eclipsesource.com/technology/eclipse-theia"
  name = "Eclipse Theia IDE"
  weight = 30

[[menu.footer]]
  url = "https://eclipse.dev/che"
  name = "Eclipse Che"
  weight = 50

[[menu.copyright_footer]]
  url = "https://projects.eclipse.org/projects/ecd.emfcloud"
  name = "About"
  weight = 5

[[menu.copyright_footer]]
  url = "https://www.eclipse.org/legal/privacy.php"
  name = "Privacy Policy"
  weight = 10

[[menu.copyright_footer]]
  url = "https://www.eclipse.org/legal/termsofuse.php"
  name = "Terms of Use"
  weight = 20

[[menu.copyright_footer]]
  url = "https://www.eclipse.org/legal/copyright.php"
  name = "Copyright"
  weight = 30

[[menu.copyright_footer]]
  url = "https://www.eclipse.org/legal/"
  name = "Legal"
  weight = 40


[[menu.footer_social]]
  weight = 20
  name = "twitter"
  pre = "fab fa-twitter"
  url = "https://twitter.com/emfcloud"

  [[menu.footer_social]]
  weight = 30
  name = "github"
  pre = "fab fa-github"
  url = "https://github.com/eclipse-emfcloud/emfcloud"

[[menu.footer_social]]
  weight = 30
  name = "github-discussions"
  pre = "far fa-comments"
  url = "https://github.com/eclipse-emfcloud/emfcloud/discussions"
